// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Support des variables Supabase et standard
    url: process.env["DIRECT_DATABASE_URL"] || process.env["POSTGRES_URL_NON_POOLING"] || process.env["DIRECT_URL"],
  },
});
